# Generated by Django 3.0.7 on 2020-06-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summery',
            new_name='summary',
        ),
    ]
